theme: jekyll-theme-minimal
title: ğŸ’»âœ’ï¸ğŸ“„ğŸŒŸ
description: Vagia Chouchouli's CV
show_downloads: 'true'
docs:
  pdf_url: 'docs/CV_Chouchouli Vaia.pdf'
  doc_url: 'docs/CV_Chouchouli Vaia.doc'

